spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2     # (1) Context path
#  datasource:
#    url: jdbc:h2:mem:test     # (2) JDBC URL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studycommunity?useSSL=false&serverTimezone=UTC
    username: root
    password: ${ROOT_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # 스키마 자동 생성
    show-sql: false    # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420